#!/usr/bin/env sh
# Create the lmdb inputs
# N.B. set the path to the imagenet train + val data dirs

#EXAMPLE=examples/tianchi
DATA=data/tianchi
TOOLS=build/tools

if [ $# -ne 6 ]; then
	echo "Usage: ./create_lmdb.sh imgname_dir data_dir dst_dir start_batch end_batch flag"
	echo " e.g., ./create_lmdb.sh imagename_batches eval_image lmdb_batches 6 10 1"
	echo "       ./create_lmdb.sh query_imagename.txt query_image lmdb_query 0 0 1"
	echo "-----------------------------------------------------------------------------------"
	echo "Functions:"
	echo "  to create lmdb input for neural net"
	echo "Parameters:"
	echo "  imgname_dir: the index file generated by data_setup.sh"
	echo "            just stores image filenames"
	echo "  data_dir: the directory that contain images listed in index_file"
	echo "                 data_dir/ contains the actual imageset"
	echo "  dst_dir: dir that contains converted lmdbs"
        echo "           stored in /data/jixin/tianchi/dst_dir."
	echo "  flag: whether to resize the image to 256*256"
	echo "        flag=0 means not to resize"
	echo "  start_batch: where to start resizing and creating lmdb"
	echo "               if end_batch=0, this para will be neglected"
	echo "  end_batch: the end batch number"
	echo "Notes:"
	echo "  the base path is /data/jixin/tianchi/"
	echo "  create lmdb from start_batch to last batch"
	echo "  e.g., data_root_dir=train_batches, whole path is /data/jixin/tianchi/train_batches"
	exit
fi

TRAIN_DATA_ROOT="$TIANCHI/$2"
#VAL_DATA_ROOT=/path/to/imagenet/val/

# Set RESIZE=true to resize the images to 256x256. Leave as false if images have
# already been resized using another tool.
if [ $6 = 0 ]; then
	RESIZE=false
else 
	RESIZE=true
fi

if $RESIZE; then
  RESIZE_HEIGHT=256
  RESIZE_WIDTH=256
else
  RESIZE_HEIGHT=0
  RESIZE_WIDTH=0
fi

if [ ! -d "$TRAIN_DATA_ROOT" ]; then
  echo "Error: TRAIN_DATA_ROOT is not a path to a directory: $TRAIN_DATA_ROOT"
  echo "Set the TRAIN_DATA_ROOT variable in create_imagenet.sh to the path" \
       "where the ImageNet training data is stored."
  exit 1
fi

#if [ ! -d "$VAL_DATA_ROOT" ]; then
#  echo "Error: VAL_DATA_ROOT is not a path to a directory: $VAL_DATA_ROOT"
#  echo "Set the VAL_DATA_ROOT variable in create_imagenet.sh to the path" \
#       "where the ImageNet validation data is stored."
#  exit 1
#fi

echo "Creating train lmdb..."

# $TRAIN_DATA_ROOT/batch$i is the actual data dir
# $TIANCHI/$1/batch$i.txt is the index file dir
if [ $5 = 0 ]; then
GLOG_logtostderr=1 $TOOLS/convert_imageset \
    --resize_height=$RESIZE_HEIGHT \
    --resize_width=$RESIZE_WIDTH \
    --shuffle \
    $TRAIN_DATA_ROOT/ \
    $DATA/$1 \
    $TIANCHI/$3
else
if [ ! -d "$TIANCHI/$3" ]; then
        mkdir $TIANCHI/$3
fi
for i in $( seq $( expr $4 - 1 ) $( expr $5 - 1) )
do
echo batch$i
GLOG_logtostderr=1 $TOOLS/convert_imageset \
    --resize_height=$RESIZE_HEIGHT \
    --resize_width=$RESIZE_WIDTH \
    --shuffle=false \
    $TRAIN_DATA_ROOT/ \
    $DATA/$1/batch$i.txt \
    $TIANCHI/$3/lmdb_batch$i
done
fi

#echo "Creating val lmdb..."

#GLOG_logtostderr=1 $TOOLS/convert_imageset \
#    --resize_height=$RESIZE_HEIGHT \
#    --resize_width=$RESIZE_WIDTH \
#    --shuffle \
#    $VAL_DATA_ROOT \
#    $DATA/val.txt \
#    $EXAMPLE/ilsvrc12_val_lmdb

echo "Done."
